apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2020-01-20T14:07:17Z
  generation: 1
  name: web-dashboard
  namespace: default
  resourceVersion: "2659"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/web-dashboard
  uid: 2a719459-3b8e-11ea-ab89-0242ac110028
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: web-dashboard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: web-dashboard
    spec:
      containers:
      - image: kodekloud/my-kubernetes-dashboard
        imagePullPolicy: Always
        name: web-dashboard
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: dashboard-sa
      serviceAccountName: dashboard-sa
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-01-20T14:07:55Z
    lastUpdateTime: 2020-01-20T14:07:55Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2020-01-20T14:07:17Z
    lastUpdateTime: 2020-01-20T14:07:55Z
    message: ReplicaSet "web-dashboard-795df6d544" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1