apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2020-01-20T09:39:31Z
  generateName: web-dashboard-795df6d544-
  labels:
    name: web-dashboard
    pod-template-hash: "3518928100"
  name: web-dashboard-795df6d544-n5dp9
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: web-dashboard-795df6d544
    uid: c246c88f-3b68-11ea-b756-0242ac110046
  resourceVersion: "4504"
  selfLink: /api/v1/namespaces/default/pods/web-dashboard-795df6d544-n5dp9
  uid: c248cbf2-3b68-11ea-b756-0242ac110046
spec:
  containers:
  - image: kodekloud/my-kubernetes-dashboard
    imagePullPolicy: Always
    name: web-dashboard
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-nhcpx
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: node01
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-nhcpx
    secret:
      defaultMode: 420
      secretName: default-token-nhcpx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2020-01-20T09:39:31Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2020-01-20T09:39:40Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2020-01-20T09:39:31Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f62de8ea3198af382e206710d45e5871566fd54431dd2373312878eba73e2b59
    image: kodekloud/my-kubernetes-dashboard:latest
    imageID: docker-pullable://kodekloud/my-kubernetes-dashboard@sha256:51261309eebea4f4d2224fe95dcbb664e0fea03bbaecb4ec930fb972c475d927
    lastState: {}
    name: web-dashboard
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2020-01-20T09:39:39Z
  hostIP: 172.17.0.72
  phase: Running
  podIP: 10.32.0.2
  qosClass: BestEffort
  startTime: 2020-01-20T09:39:31Z