apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs-1
  labels:
   env: dev
   app: webapp-1
spec: 
  replicas: 3
  template:
    metadata:
       name: webapp-1
       labels:
         env: dev
         type: web
         app: webapp-1
    spec:
      containers:
        - name: nginx-webserver
          image: nginx:latest
  selector:
    matchLabels:
               app: webapp-1
