=======================================================================
                         NETWORK  - BASICS-1 
 =======================================================================


#To set ipaddress to two systems and connect them through switch(192.168.1.0)
   
 Classless inter-domain routing (CIDR):
  https://www.geeksforgeeks.org/classless-inter-domain-routing-cidr/
  
  #To see the network interfaces IN LINUX:
    ip link
    
 network -1:
   s-1:
     ip addr add 192.168.1.10/24 dev eth0
   s-2:
     ip addr add 192.168.1.11/24 dev eth0
     
   switch-1:
     s-1 and s-2 can connect through switch-1:  192.168.1.0
 
 network -2:
    s-3:
      ip addr add 192.168.2.10/24 dev eth0
    s-4:
      ip addr add 192.168.2.10/24 dev eth0
      
    switch-2: 
    s-3 and s-4 can connect through switch-2: 192.168.2.0
    

 router: 
  network -1 and network -2 can connect to 'router' through switch1 and 2
  
  has two ip address of networks-1,2  i.e  192.168.1.1 and 192.168.2.1
  
  These details should be present in route tables to connect two networks-1
  
  #To add these networks
    ip route add 192.168.2.0/24 via 192.168.1.1
    ip route add 192.168.1.0/24 via 192.168.2.1
    to add these ip's permanantly  if not added when we restrt these gets deleted.
      etc/network/interfaces
    
    #to add default gateway 
     ip route add default via 192.168.2.1
     #or 
     ip route add 0.0.0.0 via 192.168.2.1
    
    #enable comm b/w two interfaces eth0,1  0 - prvt and 1 - pub
    cat proc/sys/net/ipv4/ip_forward   # default value is 0 to establish comm set value to 1
    also change in /etc/sysctl.conf 
      net.ipv4.ip_forward=1
   
    #To setup hostname in linux
    cat >> /etc/hosts
    192.168.2.10 db #assigning name to ip is called as name resolution
    #now u can ping the system with  below command instead of ip
     ping db 
    
    #To add entry in DNS server 
    cat /etc/resolve.conf
    nameserver        192.168.1.100  #internal dns server
    www.facebook.com   8.8.8.8     #we dont know facebooks ip so we added dns who knows all ip's 8.8.8.8
    
    - First  ping looks for 'hosts' file and then 'resolve.conf' file for name 'db'
      This is configured in  /etc/nsswitch.conf
    
  www.facebook.com
  
   - www -> sub-domain
   - facebook -> domain-name
   - com -> top-level-domain  
     #.com - commercial, .net- network, .org - Non-profit-organization, .edu - educational
  
  #to resolve name  i.e www.facebook.com
    looks in local hosts file -> Our DNS server -> public DNS server -> .com DNS server -> facebook DNS
  
  #Record types in DNS server:
    A     web-server 192.168.0.1 # stores ipv4 address 
    AAAA  web-server 2190:219e:2901:7834:d2e8:f892:29e9:2910 # stores ipv6 address
    CNAME food.webserver.com eat.web-server.com # stores sub-domains
 
  #TO get the public ip address in linux use command 
   nslookup www.google.com
   dig www.google.com #gives more detailed info
  
  #TO see about DNS server
  https://github.com/kubernetes/dns/blob/master/docs/specification.md
  https://coredns.io/plugins/kubernetes/