================================================================= 
                        REPLICA SET
================================================================= 


---------------ReplicaSet-definition.yml---------------
#note: the appVersion should be apps/v1 for ReplicationController
#if apiVersion is v1 , we can get error unable to recognize
 apiVersion: apps/v1
 kind: ReplicaSet
 metadata: 
   name: webserver-replicaset
   labels:
     app: webserver
     type: front-end    
 spec:
   template:  
     metadata: 
       name: webserver-pod
       labels:
         app: webserver
         type: front-end    
     spec:
       container:
         - name: nginx-controller
           image: nginx  
   replicas: 3
   selector: #for repicaset selector is used as additonal feild
     matchLabels:
       app: webserver
       type: front-end
----------------commands to create replica sets----------------------------

#To create replicaset using above file.
 kubectl create -f replicaset-definition.yml
 
#To edit the replicaSet(say rs name: webserver-replicaset)
 kubectl edit rs <replicaset-name>
 #ex: kubectl edit rs webserver-replicaset

#To export replicaset to yaml file
 kubectl get rs webserver-replicaset -o yaml > rs.yml
#-----------------------------------------------
#To increase the no. of replicas to 6 
#change the replicas to 6 in the above file
#then run the below command
 kubectl replace -f replicaset-definition.yml

#or  we can do using tags for above file
 kubectl scale --replicas=6 -f replicaset-definition.yml

#or  we can do using type and name format
 kubectl scale --replicas=6 replicaset myapp-replicaset
#-----------------------------------------------------

#To see created replicaset
 kubectl get replicaset
#note: we can see desired-current-ready status

#To see no of pods created after running replica-set
 kubectl get pods -o wide
#Note: we can see three pods if we used above to file to create replicas

#To remove the replicaset and also pods underlying
 kubectl delete replicaset webserver-replicaset

-----------------------------------------------------------------